### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by awarenessaspie** [patrickrchao/JailbreakingLLMs#14]
Traceback (most recent call last):
  File "C:\Users\hawke\JailbreakingLLMs\main.py", line 188, in <module>
    main(args)
  File "C:\Users\hawke\JailbreakingLLMs\main.py", line 38, in main
    extracted_attack_list = attackLM.get_attack(convs_list, processed_response_list)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hawke\JailbreakingLLMs\conversers.py", line 86, in get_attack
    full_prompts.append(conv.get_prompt()[:-len(conv.sep2)])
                                            ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

I encounter this error. What should I do?

**Comment by dirtycomputer** [comment]
same question

**Comment by dirtycomputer** [comment]
`extracted_attack_list = [attack for attack in extracted_attack_list if attack is not None]`

**Comment by xndong** [comment]
Very toxic repo to the community, I believe. I spent 2 days to fix many bugs in their repos.

**Comment by Good-Way-ZJU** [comment]
> Very toxic repo to the community, I believe. I spent 2 days to fix many bugs in their repos.

Can't agree more, I think the system prompt can't make sure that the attacke LLM output the desired json format, which causes this issue. sep2 can be set manually, but I still encounter this  
/PAIR/main.py", line 46, in <listcomp>
    adv_prompt_list = [attack["prompt"] for attack in extracted_attack_list]
TypeError: 'NoneType' object is not subscriptable
